ALTER TABLE services
  ADD COLUMN IF NOT EXISTS tagline   TEXT,
  ADD COLUMN IF NOT EXISTS highlight TEXT,
  ADD COLUMN IF NOT EXISTS color     TEXT NOT NULL DEFAULT 'from-red-600 to-rose-700',
  ADD COLUMN IF NOT EXISTS category  TEXT NOT NULL DEFAULT 'service',
  ADD COLUMN IF NOT EXISTS cta       TEXT DEFAULT 'ติดต่อเลย',
  ADD COLUMN IF NOT EXISTS badge     TEXT;
